import React, { useEffect } from 'react';
import { Outlet } from 'react-router-dom';
import { Navbar } from './Navbar';
import { useAuthStore } from '../../store';
import { Loading, FeatureHelp } from '../common';

const availableFeatures = [
  {
    title: 'Invoice Management',
    description: 'Create, edit, view, and delete invoices with full lifecycle support (Draft → Sent → Paid)',
    available: true,
  },
  {
    title: 'Invoice Status Updates',
    description: 'Update invoice status with validation. Quick "Mark as Paid" button for SENT/OVERDUE invoices.',
    available: true,
  },
  {
    title: 'PDF Generation & Download',
    description: 'Download professional PDF invoices generated by the backend',
    available: true,
  },
  {
    title: 'Email Delivery',
    description: 'Send invoices to customers via email with PDF attachments',
    available: true,
  },
  {
    title: 'User Management',
    description: 'Create, view, edit, and delete users (Owner/Admin roles). View detailed user profiles.',
    available: true,
  },
  {
    title: 'Role-Based Access Control',
    description: 'Four user roles with different permissions: Owner, Admin, Manager, Attendant',
    available: true,
  },
  {
    title: 'Organization Settings',
    description: 'Owners can manage organization details and settings',
    available: true,
  },
  {
    title: 'Analytics Dashboard',
    description: 'View invoice summary statistics and revenue tracking',
    available: true,
  },
  {
    title: 'Invoice Export',
    description: 'Export invoices in CSV and JSON formats',
    available: true,
  },
  {
    title: 'Multi-Currency Support',
    description: 'Create and manage invoices in multiple currencies (NGN, USD, GBP, EUR) with proper formatting',
    available: true,
  },
  {
    title: 'Tax/VAT Management',
    description: 'Apply per-line-item tax rates, calculate tax breakdowns, and collect customer VAT numbers',
    available: true,
  },
  {
    title: 'Advanced Reports',
    description: 'Custom report generation with data visualization and insights',
    available: false,
  },
  {
    title: 'Customer Management',
    description: 'Dedicated customer profiles with contact history and invoice tracking',
    available: false,
  },
  {
    title: 'Product Catalog',
    description: 'Manage products/services with pricing and inventory',
    available: false,
  },
  {
    title: 'Recurring Invoices',
    description: 'Set up automatic recurring invoices for regular customers',
    available: false,
  },
  {
    title: 'Payment Gateway Integration',
    description: 'Accept online payments directly through the platform',
    available: false,
  },
];

export const DashboardLayout: React.FC = () => {
  const { user, fetchCurrentUser, isLoading } = useAuthStore();

  useEffect(() => {
    if (!user) {
      fetchCurrentUser();
    }
  }, [user, fetchCurrentUser]);

  if (isLoading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <Loading size="lg" text="Loading..." />
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50">
      <Navbar />
      <main className="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
        <Outlet />
      </main>
      <FeatureHelp features={availableFeatures} />
    </div>
  );
};
